@startuml ПриемкаТоваровНаСклад
salt

<style>
saltDiagram {
    BackgroundColor lightyellow
}
</style>

{
  ' Верхняя панель
  { [<] | [>] | [☆] | "Приемка товаров на склад" | "" | "" | "" | [link] | [⋮] | [x] }

  ' Выбор склада + кнопки справа
  { ^Центральный склад^ | "" | "" | "" | "" | "" | "" | "" | [Обновить] | [?] }

  ' Фильтры + действия + "Еще"
  {
    "Состояние:" | ^Все к приемке^ | "Дата поступления:" | " . . . " | [кал] | [x] | [+ Создать ордер] | [Этикетки] | "" | [Еще v]
  }

  ' Таблица (верхняя)
  {+
    "Номер" | "Дата" | "Тип документа" | "Отправитель" | "Состояние" | "Номер и дата входящего документа"
    " "     | " "    | " "            | " "           | " "         | " "
  }

  ..

  ' Панель над нижней таблицей
  {
    "Показать:" | ^Все^ | [Печать] | [v] | [Отчеты] | [v] | [Действие] | [v] | "" | [Еще v]
  }

  ' Таблица (нижняя)
  {+
    "Ордер на приемку" | "Номер" | "Дата  ↓" | "Статус" | "Отправитель" | "Комментарий"
    " "                | " "     | " "       | " "      | " "           | " "
  }
}
@enduml
