@startsalt АРМ_АнализаКонтрагентов1
<style>
saltDiagram {
    BackgroundColor lightyellow
}
</style>

{+ 

{*.  **Дополнительные формы**  для справочника "Контрагенты" 1/3 }

{^
.
Форма **Холдинговая структура**
{/ <b>Холдинговая структура | Общие сведения | Растениеводство | Техника клиентов на обслуживании СЦ | Парк техники Клиентов |  Потребности | Дополнительно |}
.
При выборе этой формы будет отрисована холдинговая структура
}
.
{^
Форма  **Прочее**
. 
{
{/ Холдинговая структура | <b>Общие сведения | Растениеводство | Техника клиентов на обслуживании СЦ | Парк техники Клиентов |  Потребности | Дополнительно |}
.
{ [ ] СельходТовароПроизводитель | . |
   Дата создания | . | ^01.01.2007^ | . |
   Использование ЭДО | . | ^Диадок^ | . |
   Идентификатор ЭДО | . | {+ НомерИдентификатора} }
   
{
{^<b>Показатели покупателя ()

{<b>Площадь | . | общая | . |  {+ <b>1542.30 } | . | арендованная | . |  {+ <b>245.80 }  }

{Отрасль деятельности | . |  ^Мясопереработка^}
{ABCD класс покупателя | . |  ^В - класс^}
====
Лояльность
{ Запчасти | ^Лояльный^ | .}
{ Агрохимия | ^Лояльный^ | .}
{ СХТ | ^Нелояльный^ | .}
} 
| . |

{^<b>Емкости у Контрагента

{ Емкость по минеральным удобрениям | {+ <b>  21 } | .}

{ Емкость по маслам и смазкам | {+ <b>  41 } | .}

{ Емкость по ГСМ | {+ <b>  15 } | .}
}
}

{Дополнительная информация | . | {+ <b>Многострочное текстовое поле}}

}}
.
{^
Форма **Растениеводство**
. 
{
{/ Холдинговая структура | Общие сведения | <b>Растениеводство | Техника клиентов на обслуживании СЦ | Парк техники Клиентов |  Потребности | Дополнительно |}

{С/Х год | . |  {+ 2024} | . | [Редактировать] | . | Последняя правка | . |  {+ 13.10.2023}  | . | Автор изменений | . |  {+ Эдоков Руслан Борисович}}
{#
. <b> № | <b>Посевы | <b>Площадь, га. | <b>Валовый сбор, тн. | <b>Урожайоность, ц/га 
 1 | Пшеница озимая | 10 000,00 | 95 143,45 | ??,50 
 . | . | . | . | . 
 . | . | . | . | .
}}}

}
@endsalt